name: Bump version
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/tag.yaml
      - "*.yml"
      - "*.sh"
      - "Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.35.0
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
          WITH_V: true
